update/ci_v12

diff --git a/.github/workflows/flutter-ci.yml b/.github/workflows/flutter-ci.yml
--- a/.github/workflows/flutter-ci.yml
+++ b/.github/workflows/flutter-ci.yml
@@ -114,109 +114,109 @@ jobs:
             echo "TAG_EXISTS=false" >> $GITHUB_ENV
           fi
 
-      # Modify Tag if it Exist
-      - name: Modify Tag
-        if: env.TAG_EXISTS == 'true'
-        id: modify_tag
-        run: |
-          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
-          echo "VERSION=$new_version" >> $GITHUB_ENV
-
-      - name: Determine new tag version
-        id: determine_new_tag
-        run: |
-          # Get the latest tag
-          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
-
-          # Remove leading 'v' if present and split the version into parts
-          VERSION=${LATEST_TAG#v}
-
-          # Ensure the version follows the expected format
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Invalid latest tag format: $LATEST_TAG"
-          exit 1
-          fi
-
-          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
-
-          # Increment the patch version
-          NEW_PATCH=$((PATCH + 1))
-          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"
-
-          echo "New tag will be: $NEW_TAG"
-          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
-
-      - name: Create and push new tag
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git tag "$NEW_TAG"
-          git push origin "$NEW_TAG"
-        env:
-          GITHUB_TOKEN: ${{ secrets.PUB_DEV_CREDENTIALS }}
-
-      - name: Create GitHub Release
-        uses: ncipollo/release-action@v1
-        with:
-          tag: ${{ github.ref_name }}
-          name: Release ${{ github.ref_name }}
-          body: |
-            Automated release for tag ${{ github.ref_name }}.
-        env:
-          GITHUB_TOKEN: ${{ secrets.PUB_DEV_CREDENTIALS }}
-
-#      - name: Create GitHub Release
-#        uses: softprops/action-gh-release@v2
-#        with:
-#          tag_name: ${{ github.ref_name }}
-#          name: Release ${{ github.ref_name }}
-#          body: |
-#            Changes in this release:
-#            - Feature 1
-#            - Bugfix 2
-#            - Improvement 3
-#          draft: false  # Set to true if you want a draft release
-#          prerelease: false  # Set to true if it's a pre-release
+#      # Modify Tag if it Exist
+#      - name: Modify Tag
+#        if: env.TAG_EXISTS == 'true'
+#        id: modify_tag
+#        run: |
+#          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
+#          echo "VERSION=$new_version" >> $GITHUB_ENV
+#
+#      - name: Determine new tag version
+#        id: determine_new_tag
+#        run: |
+#          # Get the latest tag
+#          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
+#
+#          # Remove leading 'v' if present and split the version into parts
+#          VERSION=${LATEST_TAG#v}
+#
+#          # Ensure the version follows the expected format
+#          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#          echo "Invalid latest tag format: $LATEST_TAG"
+#          exit 1
+#          fi
+#
+#          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
+#
+#          # Increment the patch version
+#          NEW_PATCH=$((PATCH + 1))
+#          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"
+#
+#          echo "New tag will be: $NEW_TAG"
+#          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
+#
+#      - name: Create and push new tag
+#        run: |
+#          git config --global user.name "github-actions[bot]"
+#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#          git tag "$NEW_TAG"
+#          git push origin "$NEW_TAG"
 #        env:
 #          GITHUB_TOKEN: ${{ secrets.PUB_DEV_CREDENTIALS }}
-
-  publish:
-    permissions:
-      id-token: write # Required for authentication using OIDC
-    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
-    with:
-      environment: 'PUB_DEV_CREDENTIALS'
-      # working-directory: path/to/package/within/repository
-
-#  release:
-#    name: Release + Publish
-#    runs-on: ubuntu-latest
-#    needs: build-test
-#    if: startsWith(github.ref, 'refs/tags/v')
-#
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#
-#      - name: Setup Flutter
-#        uses: subosito/flutter-action@v2
-#        with:
-#          channel: stable
-#          flutter-version: 3.24.4
-#          cache: true
-#
-#      - name: Install dependencies
-#        run: flutter pub get
-#
-#      # Publish package to pub.dev (OIDC recommended if configured)
-#      - name: Publish to pub.dev
-#        run: dart pub publish --force
 #
 #      - name: Create GitHub Release
 #        uses: ncipollo/release-action@v1
 #        with:
 #          tag: ${{ github.ref_name }}
 #          name: Release ${{ github.ref_name }}
-#          generateReleaseNotes: true
+#          body: |
+#            Automated release for tag ${{ github.ref_name }}.
 #        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          GITHUB_TOKEN: ${{ secrets.PUB_DEV_CREDENTIALS }}
+#
+##      - name: Create GitHub Release
+##        uses: softprops/action-gh-release@v2
+##        with:
+##          tag_name: ${{ github.ref_name }}
+##          name: Release ${{ github.ref_name }}
+##          body: |
+##            Changes in this release:
+##            - Feature 1
+##            - Bugfix 2
+##            - Improvement 3
+##          draft: false  # Set to true if you want a draft release
+##          prerelease: false  # Set to true if it's a pre-release
+##        env:
+##          GITHUB_TOKEN: ${{ secrets.PUB_DEV_CREDENTIALS }}
+#
+#  publish:
+#    permissions:
+#      id-token: write # Required for authentication using OIDC
+#    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
+#    with:
+#      environment: 'PUB_DEV_CREDENTIALS'
+#      # working-directory: path/to/package/within/repository
+
+  release:
+    name: Release + Publish
+    runs-on: ubuntu-latest
+    needs: build-test
+    if: startsWith(github.ref, 'refs/tags/v')
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          channel: stable
+          flutter-version: 3.24.4
+          cache: true
+
+      - name: Install dependencies
+        run: flutter pub get
+
+      # Publish package to pub.dev (OIDC recommended if configured)
+      - name: Publish to pub.dev
+        run: dart pub publish --force
+
+      - name: Create GitHub Release
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ github.ref_name }}
+          name: Release ${{ github.ref_name }}
+          generateReleaseNotes: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
